In [1]:
import numpy as np

In [8]:
arr = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
mean_axis1 = np.mean(arr, axis=0)
mean_axis2 = np.mean(arr, axis=1)
mean = np.mean(arr)
print(mean_axis1, mean_axis2, mean)

[3. 4. 5.] [1. 4. 7.] 4.0


In [14]:
var_axis1 = np.var(arr, axis=0)
var_axis2 = np.var(arr, axis=1)
var = np.var(arr)
print(var_axis1, var_axis2, var)

[6. 6. 6.] [0.66666667 0.66666667 0.66666667] 6.666666666666667


In [23]:
std_axis1 = np.std(arr, axis=0)
std_axis2 = np.std(arr, axis=1)
std = np.std(arr)
print(std_axis1, std_axis2, std)

[2.44948974 2.44948974 2.44948974] [0.81649658 0.81649658 0.81649658] 2.581988897471611


In [27]:
max_axis1= np.max(arr, axis=0)
max_axis2= np.max(arr, axis=1)
max = np.max(arr)
print(max_axis1, max_axis2, max)

[6 7 8] [2 5 8] 8


In [28]:
min_axis1 = np.min(arr, axis=0)
min_axis2 = np.min(arr, axis=1)
min = np.min(arr)
print(min_axis1, min_axis2, min)

[0 1 2] [0 3 6] 0


In [29]:
sum_axis1 = np.sum(arr, axis=0)
sum_axis2 = np.sum(arr, axis=1)
sum = np.sum(arr)
print(sum_axis1, sum_axis2, sum)

[ 9 12 15] [ 3 12 21] 36


In [1]:
import numpy as np

def convert_to_3x3_array(digits_list):
    # Check if the input list has exactly 9 elements
    if len(digits_list) != 9:
        raise ValueError("List must contain nine digits.")

    # Convert the list to a 3x3 NumPy array
    array_3x3 = np.array(digits_list).reshape(3, 3)

    return array_3x3

# Example usage:
digits_list = [9,1,5,3,3,3,2,9,0]
result_array = convert_to_3x3_array(digits_list)
print(result_array)

[[9 1 5]
 [3 3 3]
 [2 9 0]]


In [2]:
result = {
        'meam' : [mean_axis1, mean_axis2, mean],
        'variance' : [var_axis1, var_axis2, var],
        'standard deviation' : [std_axis1, std_axis2, std],
        'max' : [max_axis1, max_axis2, max],
        'min' : [min_axis1, min_axis2, min],
        'sum' : [sum_axis1, sum_axis2, sum],
    }
    
print(result)

NameError: name 'mean_axis1' is not defined

In [13]:
import numpy as np

def calculate(input_list):

    if len(input_list) !=9:
        raise ValueError("List must contain nine numbers")
    
    
    arr = np.array(input_list).reshape(3,3)

    mean_axis1 = np.mean(arr, axis=0)
    mean_axis2 = np.mean(arr, axis=1)
    mean = np.mean(arr)

    var_axis1 = np.var(arr, axis=0)
    var_axis2 = np.var(arr, axis=1)
    var = np.var(arr)

    std_axis1 = np.std(arr, axis=0)
    std_axis2 = np.std(arr, axis=1)
    std = np.std(arr)

    max_axis1 = np.max(arr, axis=0)
    max_axis2 = np.max(arr, axis=1)
    max = np.max(arr)

    min_axis1 = np.min(arr, axis=0)
    min_axis2 = np.min(arr, axis=1)
    min = np.min(arr)

    sum_axis1 = np.sum(arr, axis=0)
    sum_axis2 = np.sum(arr, axis=1)
    sum = np.sum(arr)

    result = {
        'mean' : [mean_axis1, mean_axis2, mean],
        'variance' : [var_axis1, var_axis2, var],
        'standard deviation' : [std_axis1, std_axis2, std],
        'max' : [max_axis1, max_axis2, max],
        'min' : [min_axis1, min_axis2, min],
        'sum' : [sum_axis1, sum_axis2, sum]
    }

    return result

In [14]:
calculate([9,1,5,3,3,3,2,9,0])

{'mean': [array([4.66666667, 4.33333333, 2.66666667]),
  array([5.        , 3.        , 3.66666667]),
  3.888888888888889],
 'variance': [array([ 9.55555556, 11.55555556,  4.22222222]),
  array([10.66666667,  0.        , 14.88888889]),
  9.209876543209875],
 'standard deviation': [array([3.09120617, 3.39934634, 2.05480467]),
  array([3.26598632, 0.        , 3.8586123 ]),
  3.0347778408328137],
 'max': [array([9, 9, 5]), array([9, 3, 9]), 9],
 'min': [array([2, 1, 0]), array([1, 3, 0]), 0],
 'sum': [array([14, 13,  8]), array([15,  9, 11]), 35]}